#  ----------------------------------------------------
#  Alliances Configuration File
#  ----------------------------------------------------

# How to store all data
# Availiable types are mysql and sqlite

storage:
  type: sqlite
  host: localhost
  port: 3306
  database: 'elchilen0'
  username: 'root'
  password: 'root'
  tablePrefix: 'alliance_'

# Some small alliance options
alliance:
  allianceAllowBans: true
  purgeInactivePlayerDays: 25
  purgeInactiveClanDays: 50

# Chat colors for faction states and members
chat:
# Each prefix must be a chat color without & before it
  memberPrefix: 'a'
  neuturalPrefix: 'f'
  partnerPrefix: 'd'
  brotherPrefix: 'b'
  enemyPrefix: 'c'
  warPrefix: '4'
  moderatorPrefix: '*'
  leaderPrefix: '**'
  allianceTagMaxSize: 8
  allianceDescMaxSize: 64
  allianceObjectiveMaxSize: 64
  
# Each action can cost a certain configurable amount
economy:
  enabled: true
# Zone costs ------------------------------------------
  warZoneCost: 0
  safeZoneCost: 0
  plotZoneCost: 100
# Command costs ---------------------------------------
  createAllianceCost: 35000
  disbandAllianceCost: 500
  setAllianceHomeCost: 100
  setAllianceDescCost: 500
  setAllianceObjectiveCost: 100
  openAllianceCost: 5000
  inviteCost: 0
  uninviteCost: 0
  kickCost: 0
  joinAllianceCost: 0
  leaveAllianceCost: 0
  partnerAllianceCost: 0
  brotherAllianceCost: 5000
  enemyAllianceCost: 0
  rivalAllianceCost: 500
# Kill rewards ----------------------------------------
  rewardNeutural: 0
  rewardPartner: 0
  rewardBrother: 0
  rewardEnemy: 10
  rewardRival: 50

# Zones are claimable chunks for both player and admins
zones:
# War zones -------------------------------------------
  warZoneFriendlyFire: true
  warZoneBlockDamage: false
  warZonePlayerDamage: true
  warZoneDenyUsage: false
  warZoneDenyBuild: false
# Safe zones ------------------------------------------
  safeZoneFriendlyFire: false
  safeZoneBlockDamage: false
  safeZonePlayerDamage: false
  safeZoneDenyUsage: true
  safeZoneDenyBuild: true
# Plot zones ------------------------------------------
  plotZoneFriendlyFire: false
  plotZoneStrangerDenyBlockDamage: true
  plotZoneStrangerDenyPlayerDamage: true
  plotZoneStrangerDenyUsage: false
  plotZoneStrangerDenyBuild: true
  
# Any additional configuration
other:
  maxClaims: 20
  deletePlayerDataOnBan: true
  deletePlayerDataAfterDaysOfInactivity: 50
  disabledWorlds:
    - world_the_nether
    - world_the_end